spec:
  name: ocr-microservice
  services:
  - name: web
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    source_dir: /
    git:
      branch: main
      repo_clone_url: https://github.com/codingforentrepreneurs/FastAPI-Microservice-for-Django.git
    envs:
    - key: DEBUG
      value: "0"
    - key: ECHO_ACTIVE
      value: "0"
    - key: APP_AUTH_TOKEN
      value: "CHANGE_AND_ENCRYPT_ME"
      # ملف التكوين YAML
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    ports:
      - 8080:8080
